[mgr]

prepend_keymap = [
    { on = "v",  run = "shell 'nvim \"$@\"' --confirm --block", desc = "Open in nvim" },
    { on = "V",  run = "shell 'nvr \"$@\"' --confirm",          desc = "Open in nvr" },

    { on = "a",  run = "toggle_all",                            desc = "Toggle all selection" },
    { on = "r",  run = "rename --cursor=before_ext",            desc = "Rename append" },

    { on = [ "g", "c" ], run = "cd ~/.config/home-manager",     desc = "Go to config" },
    { on = [ "g", "p" ], run = "cd ~/projects",                 desc = "Go to projects" },
]
