[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.vi_mode_style]
blinking = "On"

[font]
size = 20

[font.bold]
family = "Terminess Nerd Font Mono"

[font.italic]
family = "Terminess Nerd Font Mono"

[font.normal]
family = "Terminess Nerd Font Mono"
style = "Regular"
