#!/usr/bin/env bash

choice=$(printf "localhost\nwork-machine" | fzf --prompt="Выбери подключение: ")

if [[ -z "$choice" ]]; then
    exit 0
fi

case "$choice" in
    localhost)
        harlequin -a postgres --theme gruvbox \
            postgresql://postgres:postgres@localhost:5432/postgres
        ;;
    work-machine)
        harlequin -a postgres --theme gruvbox \
            postgresql://postgres:postgres@10.66.66.2:5432/postgres
        ;;
esac
