#!/bin/sh

label='#d79921'
value='#ebdbb2'

layout=$(xkblayout-state print '%s' 2>/dev/null)
[ -n "$layout" ] || layout='?'

printf '<span foreground="%s"></span> <span foreground="%s">%s</span>\n' \
    "$label" \
    "$value" \
    "$layout"
