#!/bin/sh
label='#d79921'; normal='#ebdbb2'; warning='#fe8019'; critical='#fb4934'
set -- $(awk '/^MemTotal:/ {t=$2} /^MemAvailable:/ {a=$2} END {u=t-a; p=t>0?u*100/t:0; printf "%d %d %d\n",u,t,p}' /proc/meminfo)
used_kib=$1; total_kib=$2; percent=$3
used_gib=$(awk -v v="$used_kib" 'BEGIN {printf "%.1f",v/1048576}')
total_gib=$(awk -v v="$total_kib" 'BEGIN {printf "%.1f",v/1048576}')
color=$normal
if [ "$percent" -ge 90 ]; then color=$critical; elif [ "$percent" -ge 75 ]; then color=$warning; fi
printf '<span foreground="%s"></span> <span foreground="%s">%s/%sG</span>\n' "$label" "$color" "$used_gib" "$total_gib"
